=== hupda-edpe/p/unicorn/EapImport/src/test/resources/Testaaa.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="Testaaa.xsd" targetNamespace="Testaaa.xsd" >
    <xs:element name="Testaaa">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:Integer" name="a"/>
                <xs:element type="xs:String" name="b"/>
                <xs:element type="xs:dateTime" name="c"/>
                <xs:element type="xs:Integer" name="d"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hupda-edpe/p/unicorn/EapImport/src/test/resources/Testaaa.xml
<?xml version="1.0" encoding="UTF-8"?>
<Testaaa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="Testaaa.xsd">
	<a>3</a>
	<a>4</a>
	<b>auto</b>
	<b>Bahn</b>
   <c>2014-09-05T20:05:32.000+0200</c>
   <d>1</d>
	<d>2</d>
</Testaaa>
